mod serialization;
mod state_looks;
mod text_scale;
mod tooltip;

use crate::widgets::theme::Theme;
use crate::widgets::theme::button::ButtonTheme;
use crate::widgets::theme::context_menu::{ContextMenuTheme, MenuItemTheme};
use crate::widgets::theme::drag_value::DragValueTheme;
use crate::widgets::theme::modal::ModalTheme;
use crate::widgets::theme::palette::Palette;
use crate::widgets::theme::progress_bar::ProgressBarTheme;
use crate::widgets::theme::scrollbar::ScrollbarTheme;
use crate::widgets::theme::separator::SeparatorTheme;
use crate::widgets::theme::slider::SliderTheme;
use crate::widgets::theme::spinner::SpinnerTheme;
use crate::widgets::theme::splitter::SplitterTheme;
use crate::widgets::theme::text_edit::TextEditTheme;
use crate::widgets::theme::text_style::TextStyle;
use crate::widgets::theme::toggle::ToggleTheme;
use crate::widgets::theme::tooltip::TooltipTheme;
use crate::widgets::theme::widget_look::{AnimatedLook, StatefulLook, WidgetLook};
use static_assertions::assert_not_impl_any;

assert_not_impl_any!(Theme: Copy);
assert_not_impl_any!(ButtonTheme: Copy);
assert_not_impl_any!(ContextMenuTheme: Copy);
assert_not_impl_any!(MenuItemTheme: Copy);
assert_not_impl_any!(DragValueTheme: Copy);
assert_not_impl_any!(ModalTheme: Copy);
assert_not_impl_any!(Palette: Copy);
assert_not_impl_any!(ProgressBarTheme: Copy);
assert_not_impl_any!(ScrollbarTheme: Copy);
assert_not_impl_any!(SeparatorTheme: Copy);
assert_not_impl_any!(SliderTheme: Copy);
assert_not_impl_any!(SpinnerTheme: Copy);
assert_not_impl_any!(SplitterTheme: Copy);
assert_not_impl_any!(TextEditTheme: Copy);
assert_not_impl_any!(TextStyle: Copy);
assert_not_impl_any!(ToggleTheme: Copy);
assert_not_impl_any!(TooltipTheme: Copy);
assert_not_impl_any!(AnimatedLook: Copy);
assert_not_impl_any!(StatefulLook: Copy);
assert_not_impl_any!(WidgetLook: Copy);
