window_clear = "#1a1a1a"

[button]
padding = [
    12.0,
    6.0,
]
margin = 0.0

[button.normal.background]
fill = "#3e3e3e"
radius = 4.0

[button.normal.background.stroke]
color = "#aaaaa82e"
width = 1.0

[button.hovered.background]
fill = "#4b4b4b"
radius = 4.0

[button.hovered.background.stroke]
color = "#aaaaa82e"
width = 1.0

[button.pressed.background]
fill = "#4b4b4b"
radius = 4.0

[button.pressed.background.stroke]
color = "#105577"
width = 1.0

[button.disabled.background]
fill = "#343434"
radius = 4.0

[button.disabled.background.stroke]
color = "#aaaaa82e"
width = 1.0

[button.disabled.text]
font_size_px = 16.0
color = "#878a8d"
line_height_mult = 1.2

[scrollbar]
width = 8.0
gap = 4.0
min_thumb_px = 24.0
track = "#00000000"
thumb = "#aaaaa873"
thumb_hover = "#aaaaa8a6"
thumb_active = "#aaaaa8d9"
radius = 4.0

[text_edit]
placeholder = "#aaaaa8"
caret = "#ffffff"
caret_width = 1.5
selection = "#9adbfb40"
padding = [
    8.0,
    6.0,
]
margin = 0.0

[text_edit.normal.background]
fill = "#3e3e3e"
radius = 4.0

[text_edit.normal.background.stroke]
color = "#aaaaa82e"
width = 1.0

[text_edit.focused.background]
fill = "#3e3e3e"
radius = 4.0

[text_edit.focused.background.stroke]
color = "#105577"
width = 1.5

[text_edit.disabled.background]
fill = "#343434"
radius = 4.0

[text_edit.disabled.background.stroke]
color = "#aaaaa82e"
width = 1.0

[text_edit.disabled.text]
font_size_px = 16.0
color = "#878a8d"
line_height_mult = 1.2

[text]
font_size_px = 16.0
color = "#ffffff"
line_height_mult = 1.2
